### ISSUE TITLE
Translate README.md to Urdu

### ISSUE THREAD

**Issue by Muhammad-Shahid-Jamal** [freeCodeCamp/how-to-contribute-to-open-source#780] opened 2022-08-18 10:39 UTC
My native language is Urdu and I saw there is no full version available for that file in the Urdu language.

**Comment by Muhammad-Shahid-Jamal** [comment] 2022-08-18 11:40
Hi, @erictleung  kindly assign this issue to me so I can contribute to this.

**Comment by aakarshan-raj** [comment] 2022-09-04 17:03
I think you can contribute without being assigned to it.

**Comment by m-shahzaib-anwar** [comment] 2022-10-12 07:57
you can contribute without being assigned. Just create PR

**Comment by erictleung** [comment] 2022-12-28 23:26
Closing as duplicate of https://github.com/freeCodeCamp/how-to-contribute-to-open-source/issues/485.

**Closed by erictleung** 2022-12-28 23:26 UTC
