### ISSUE TITLE
Translate README.md to Arabic Language 

### ISSUE THREAD

**Issue by Kareem-negm** [freeCodeCamp/how-to-contribute-to-open-source#589] opened 2021-09-06 10:47 UTC
Hello my native language is Arabic, and I would like to translate the readme.md to the Arabic Language .

**Comment by erictleung** [comment] 2021-09-30 16:50
Duplicate of https://github.com/freeCodeCamp/how-to-contribute-to-open-source/issues/386

**Closed by erictleung** 2021-09-30 16:50 UTC
