### ISSUE TITLE
Titles of the Challenges are not responsive

### ISSUE THREAD

**Issue by codingpixie2021** [freeCodeCamp/how-to-contribute-to-open-source#524] opened 2021-02-14 22:06 UTC

**Comment by AliSheheryar** [comment] 2021-02-15 16:39
I am alive.

**Comment by RandellDawson** [comment] 2021-02-15 16:58
@codingpixie2021 Can you be more specific about what the issue is?

**Comment by codingpixie2021** [comment] 2021-02-15 21:04
So when you minimize the window where the challenge is described every thing is responsive BUT the title
<img width="351" alt="Screenshot 2021-02-15 at 23 03 38" src="https://user-images.githubusercontent.com/69934140/107992790-188b3380-6fe2-11eb-8a38-6b2267c581d4.png">

**Comment by erictleung** [comment] 2021-02-20 17:27
@codingpixie2021 thanks for the issue. I think this belongs in the main repository. But this also appears to be noted here (https://github.com/freeCodeCamp/freeCodeCamp/issues/41090) and fixed with this pull request (https://github.com/freeCodeCamp/freeCodeCamp/pull/41124). Happy coding!

**Closed by erictleung** 2021-02-20 17:27 UTC
